version: '3'

services:
  sftp:
    image: atmoz/sftp
    volumes:
      - jupyter-notebook-work:/home/jovyan/upload
    ports:
      - ${SFTP_PORT}:22
    #    command: ${SFTP_USER}:${SFTP_PASSWORD}:::upload
    #    command: ${SFTP_USER}:${SFTP_PASSWORD}:${SFTP_USER_ID}::upload
    command: jovyan:${SFTP_PASSWORD}:1000
    networks:
      - elk

  notebook:
    image: jupyter/datascience-notebook
    command: "start-notebook.sh \
            --NotebookApp.password=${JUPYTER_PASSWORD} \
            --NotebookApp.token=${JUPYTER_TOKEN}"
    volumes:
      - jupyter-notebook-work:/home/jovyan/upload
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY}
      - MLFLOW_S3_ENDPOINT_URL=${MLFLOW_S3_ENDPOINT_URL}
    ports:
      - ${JUPYTER_PORT}:8888
    networks:
      - elk

volumes:
  jupyter-notebook-work:
    external:
      name: jupyter-notebook

networks:
  elk:
    external:
      name: elk

