version: '3'
services:
  fuseki:
    container_name: fuseki
    image: stain/jena-fuseki
    ports:
      - "8595:3030"
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FUSEKI_DATASET_1=mydataset
    volumes:
      - fuseki-data:/fuseki/

volumes:
  fuseki-data: