version: '3'
services:
  fuseki:
    container_name: fuseki
    image: stain/jena-fuseki
    ports:
      - "8595:80"
    volumes:
      - ./:/fuseki
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
