version: '3'
  services:
    fuseki:
      container_image: fuseki
      iamge: stain/jena-fuseki
      ports:
        - "8595:80"
      volumes:
        - ./:/fuseki
      environment:
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
