version: '3'

services:
  semantic-search:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8555"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - elk

networks:
  elk:
    external:
      name: elk