version: '3'

services:
  topic-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8506:8501"
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${VAULT_TOKEN}
    networks:
      - elk

networks:
  elk:
    external:
      name: elk