version: '3'

services:
  streamlit:
    container_name:  ${STREAMLIT_HOST_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${STREAMLIT_PORT:-8501}:8501
    networks:
      - elk

networks:
  elk:
    external:
      name: elk